### ISSUE TITLE
Fix no work

### ISSUE THREAD

**Issue by Zortex04** [sant0ro/habbo-web-cms#1]
The Thing you did in you're Stream and updated it Dident work

**Comment by sant0ro** [comment]
Sorry i didn't understand..

You need also install composer.
Here works 100%

**Comment by Zortex04** [comment]
How?

**Comment by Zortex04** [comment]
i think i figured out how but now im getting this error Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl

**Comment by Zortex04** [comment]
???

**Comment by sant0ro** [comment]
Yes you don't Have OpenSSL in your Apache.
Try add library of mod_ssl.so to Apache
And add library mod_ssl.dll to PhP

**Comment by sant0ro** [comment]
Also i will post maybe today new version of AzureWEB

**Comment by sant0ro** [comment]
Fixed.
