### ISSUE TITLE
Can you update your "httpd.exe" file ?

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/habbo-web-cms#4]
The file is useless, dont work for me.
I have this error:
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15552342/3830dbce-22ba-11e6-9ab0-00a725844796.png)

**Comment by sant0ro** [comment]
Please follow the tutorial from RZ;

**Comment by Anthologique** [comment]
Please, give me the download link for:
- C++ 2012 x64 and x32 Redistributable
Thanks.

**Comment by Anthologique** [comment]
Your CMS installation dont work for me, i have httpd.exe error, i will test your CMS please...

**Comment by Anthologique** [comment]
Resolved.
