### ISSUE TITLE
Impossible install Habbo Web CMS

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/habbo-web-cms#5]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15627954/89c1311e-24f4-11e6-81e5-63f45a679e48.png)

**Comment by sant0ro** [comment]
Closing this issue. You need follow the Tutorial on RaGEZONE.

Please stop creating useless issues. This issue is explained in RaGEZONE. You need install Composer.

Check the tutorial in RaGEZONE Tutorial zone.

**Comment by Anthologique** [comment]
I have follow your tutorial on Ragezone and work fine, thanks :)
