### ISSUE TITLE
Impossible connect on housekeeping !

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/habbo-web-cms#6]
When i try enter on housekeeping, i have a error.
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15632796/3347077e-259d-11e6-8c51-d8bf8391a331.png)

**Comment by sant0ro** [comment]
/theallseeingeye/web/login

**Comment by Anthologique** [comment]
When i click on "Logon" button, dont work.
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15634673/e2278d14-25c9-11e6-8bbb-1adc9f3846a3.png)

**Comment by sant0ro** [comment]
Remember: The Housekeeping Account ISN'T THE SAME of YOUR normal USER ACCOUNT.

The HK account it's the Account that you created in the Installer.

Also you need be logged in the CMS to enter HK

**Comment by Anthologique** [comment]
I have install the CMS with my Housekeeping Account.
I have this error:
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15635735/3ce36f8a-25e7-11e6-98cc-54cf6b44c87e.png)

**Comment by Anthologique** [comment]
![animation](https://cloud.githubusercontent.com/assets/6734589/15635744/52fc048a-25e7-11e6-8fcf-b348e0883834.gif)

**Comment by Anthologique** [comment]
I dont have error, dont work....

**Comment by sant0ro** [comment]
Okay, check the table of Housekeeping Accounts, try change your rank to 5. (The Housekeeping Account is with md5)

**Comment by Anthologique** [comment]
Thanks work fine 😉

**Comment by sant0ro** [comment]
Nice. You need create a new Rank. The RANK 6 in Database. I will edit the Query here and Commit.
Since the Rank 6 is important.
